### PR TITLE
Michael Robertson - Pull Request

### PR DESCRIPTION
**Pull request by AscendingAnthem**

### CODE REVIEW

**Comment by Callam7** [comment]
I chose this CV

**Comment by KiwiNate** [comment]
Nice CV Bro, I rate it. This one is the one to use :)

**Comment by TimBennett42** [comment]
This CV looks professional and is the best of the edited CVs in my opinion.

**Comment by kippj1** [comment]
Heavens to Betsy! This CV has my vote.

**Comment by woodjj1** [comment]
I believe this c.v. is the go. Good work Michael.

**Comment by LissyMcL** [comment]
This is the one.

**Comment by eallenOP** [comment]
What's a Bachelor of Information Management?

**Comment by AscendingAnthem** [comment]
I don't even know how I typed Management instead of Technology over 5 times.
It's fixed now

**Pull request merged**
